### ISSUE TITLE
Remove action that triggers the css file

### ISSUE THREAD

**Issue by ahansson89** [pippinsplugins/bbPress-Private-replies#16]
I think it is a waste to use a request for one line of css, so I am trying to remove the action that is triggering the enqueued css file:

remove_action( 'wp_enqueue_scripts', array( 'BBP_Private_Replies', 'register_plugin_styles' ), 1000 );

The above is not working. Can you help me out with htis @pippinsplugins ?? :)

**Comment by pippinsplugins** [comment]
@jrfnl's solution is correct. I'd like to leave it as a separate file for now in order to easily accommodate future styles, and to make it easier to remove entirely.
