### ISSUE TITLE
Provide option to override the default `do_not_reply` email address

### ISSUE THREAD

**Issue by sudar** [pippinsplugins/bbPress-Private-replies#19]
In the recent version of bbPress, the way subscription emails are generated is changed and I see that you have made [this commit](https://github.com/pippinsplugins/bbPress-Private-replies/commit/e842d98f3b6791c52a43a6d21c493903f11beb7c) to fix it. But unfortunately there are couple of problems in the way the default `do_not_reply` is [generated](https://github.com/pippinsplugins/bbPress-Private-replies/blob/master/bbp-private-replies.php#L250). They are documented in this bbpress [forum post](http://bbpress.org/forums/topic/problem-with-the-default-do-not-reply-email-address/) and [blog post](http://bulkwp.com/blog/using-wpmandrill-to-send-subscription-notification-from-bbpress/)

This [ticket in bbPress](https://bbpress.trac.wordpress.org/ticket/2618) fixes most of the issues with the default `do_not_reply` email address and also adds some filters so that people can change them if needed. The `do_not_reply` email address generation logic should be changed to the one that is used in the ticket so that it fixes the issues with it.

**Comment by pippinsplugins** [comment]
We now use bbPress's helper function for getting the no reply address and it's passed through a filter so it can be changed for private replies.
```php
/**
 * Retrieves the no reply address.
 *
 * @since 1.3.3
 *
 * @return string
 */
public function get_no_reply() {
	return apply_filters( 'bbp_private_replies_no_reply_address', bbp_get_do_not_reply_address() );
}
```
