### ISSUE TITLE
Filter for capability

### ISSUE THREAD

**Issue by fastlinemedia** [pippinsplugins/bbPress-Private-replies#23]
We would like to change the capability required to view private replies from moderate to administrator. Currently, there is no way to do that, so I'm proposing a new filter that would allow us to change this. Here's an example of what I'm thinking...  

```
public function get_capability() {
	return apply_filters( 'bbp_private_replies_capability', 'moderate' );
}
```

Which can be used in the various parts of the plugin where needed like so... 

`user_can( $reply_author, $this->get_capability() )`

I would be happy to submit a pull request if you think this is something you would be willing to include. Let me know! 

Thanks,
Justin

**Comment by pippinsplugins** [comment]
`plugins_loaded` loaded is probably a better hook than `init` for this, but otherwise looks great!

**Comment by jrfnl** [comment]
Uh oh.. sorry @pippinsplugins but I don't agree. `plugins_loaded` is too early as others won't have had the opportunity to register their function hooking into this hook yet.
Most plugins won't have run their own function hooked into `plugins_loaded` yet nor has the theme been loaded yet.
