### ISSUE TITLE
Add ability to mark topics private

### ISSUE THREAD

**Issue by tech55541** [pippinsplugins/bbPress-Private-replies#26]
Hello,
There should be the ability to mark full topics private. Could this be added?

Thanks.

**Comment by pippinsplugins** [comment]
I'm not currently able to do any further development on this plugin, but that would be a nice feature.

**Comment by tech55541** [comment]
What a shame. Time to find another plugin. ☹


Alex Stine
Your Tech Advisors (YTA)
Website Administrator
Website: http://yourtechadvisors.com<http://yourtechadvisors.com/>

**Comment by tech55541** [comment]
What a shame, hope you change your mind. For now, time to find another plugin.

Thanks.
